### ISSUE TITLE
Output to console.log

### ISSUE THREAD

**Issue by iwoj** [convexset/meteor-log#3]
What would be the preferred way of also outputting log messages to `console.log`? Using `Log.registerAdditionalLogHandler`?

**Comment by convexset** [comment]
It already does that. `Log.log` and such.

**Comment by iwoj** [comment]
Doesn't seem to work for me. I have to use `registerAdditionalLogHandler`.

**Comment by iwoj** [comment]
I see now. How would I prepend the log level to the `console.log` output?

**Comment by convexset** [comment]
That's something that you'll have to do yourself.

**Comment by iwoj** [comment]
It's unclear from the documentation where or how I can override the console.log output. How would I do that?

**Comment by convexset** [comment]
```
Log.displayPredicate = function display30PercentOfMessagesAtRandomAndOnlyIfInDevMode() {
    return (Math.random() < 0.3) && Meteor.isDevelopment;
}
```

**Comment by iwoj** [comment]
This is just a Boolean function. I can't prepend a string to the console log message here. I don't have access to the log message data here either.

**Comment by iwoj** [comment]
So I did this, and it seems to work ok.

```
Log.displayPredicate = () => { return false; }
Log.registerAdditionalLogHandler(function({ args, logLevel, verbosity, tags, record }) {
  if (verbosity > Log.verbosity) return;
  if(tags.indexOf("debug") >= 0)
    console.log("[DEBUG]", args.join(" "));
  else
    console.log("["+logLevel.toUpperCase()+"]", args.join(" "));
});
```
